openapi: 3.0.3
info:
  title: Employees API
  description: The full _Employees API_.
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
    description: Development environment
paths:
  /api/employees:
    get:
      summary: List employees
      description: List employees
      operationId: listEmployees
      tags:
        - employees
      parameters:
        - name: name-prefix
          in: query
          required: false
          schema:
            type: string
        - name: RequestId
          in: header
          required: false
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Employee"
                example:
                  - id: 1
                    name: John Doe
                  - id: 2
                    name: Jack Doe
    post:
      operationId: createEmployee
      tags:
        - employees
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Employee"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
  /api/employees/{id}:
    get:
      operationId: findEmployeeById
      tags:
        - employees
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
        404:
          description: Not found
    put:
      operationId: updateEmployee
      tags:
        - employees
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Employee"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
components:
  schemas:
    Employee:
      type: object
      title: Employee
      properties:
        id:
          type: integer
          format: int64
          description: The id of the employee
        name:
          type: string
          description: The name of the employee
